// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGhp6Am40OLKeb4S7QWywmbMjakOA1d0',
    appId: '1:254609094639:web:7f6405111ea774b226e81a',
    messagingSenderId: '254609094639',
    projectId: 'hrm-doorstep',
    authDomain: 'hrm-doorstep.firebaseapp.com',
    storageBucket: 'hrm-doorstep.firebasestorage.app',
    measurementId: 'G-QMGYFRLNWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBebZxi-cS36XL79MGBIRGb_E9mhj8Zk',
    appId: '1:254609094639:android:6629acee119e080a26e81a',
    messagingSenderId: '254609094639',
    projectId: 'hrm-doorstep',
    storageBucket: 'hrm-doorstep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV33amcBl8sNNAZuDo9GNPyiPhpEYfK0A',
    appId: '1:254609094639:ios:cc59188af4ebdd8526e81a',
    messagingSenderId: '254609094639',
    projectId: 'hrm-doorstep',
    storageBucket: 'hrm-doorstep.firebasestorage.app',
    iosBundleId: 'com.example.projectYear4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV33amcBl8sNNAZuDo9GNPyiPhpEYfK0A',
    appId: '1:254609094639:ios:cc59188af4ebdd8526e81a',
    messagingSenderId: '254609094639',
    projectId: 'hrm-doorstep',
    storageBucket: 'hrm-doorstep.firebasestorage.app',
    iosBundleId: 'com.example.projectYear4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGhp6Am40OLKeb4S7QWywmbMjakOA1d0',
    appId: '1:254609094639:web:889a8c18af89bf6426e81a',
    messagingSenderId: '254609094639',
    projectId: 'hrm-doorstep',
    authDomain: 'hrm-doorstep.firebaseapp.com',
    storageBucket: 'hrm-doorstep.firebasestorage.app',
    measurementId: 'G-M0Z4TYC4SH',
  );
}
